name: cube_framework
description: Cube Framework
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
